package net.fijma.vigenere;

import org.junit.Assert;

public class TestAnalysis {

    @org.junit.Test
    public void testTable() {

        String plain = "WELKELETTERSWORDENINHETNEDERLANDSHETMEESTGEBRUIKTDEONDERSTAANDELIJSTISGEBASEERDOPONDERZOEKUITVANDESTICHTINGVOORPUBLIEKSVOORLICHTINGOVERWETENSCHAPENTECHNIEKPWTVOORHAARONDERZOEKNAARLETTERFREQUENTIESBASEERDEDESTICHTINGZICHOPEENCORPUSVANANDERHALFMILJOENWOORDENREDACTIONELEKRANTENTEKSTAFKOMSTIGUITDEHAARLEMSECOURANTGETELDEINDOVEREENPERIODEVANONGEVEERVIERMAANDENDEGEGEVENSZIJNTEVINDENINTERSPRAKESPRAAKALSBETEKENISVOLGELUIDINTHEMATISCHEHOOFDSTUKKENVANMARCELPRBROECKETOENMALIGMEDEWERKERVANDEPWT";
        String crypt = "JRYXRYRGGREFJBEQRAVAURGARQREYNAQFURGZRRFGTROEHVXGQRBAQREFGNNAQRYVWFGVFTRONFRREQBCBAQREMBRXHVGINAQRFGVPUGVATIBBECHOYVRXFIBBEYVPUGVATBIREJRGRAFPUNCRAGRPUAVRXCJGIBBEUNNEBAQREMBRXANNEYRGGRESERDHRAGVRFONFRREQRQRFGVPUGVATMVPUBCRRAPBECHFINANAQREUNYSZVYWBRAJBBEQRAERQNPGVBARYRXENAGRAGRXFGNSXBZFGVTHVGQRUNNEYRZFRPBHENAGTRGRYQRVAQBIRERRACREVBQRINABATRIRREIVREZNNAQRAQRTRTRIRAFMVWAGRIVAQRAVAGREFCENXRFCENNXNYFORGRXRAVFIBYTRYHVQVAGURZNGVFPURUBBSQFGHXXRAINAZNEPRYCEOEBRPXRGBRAZNYVTZRQRJREXREINAQRCJG";
        Assert.assertEquals('A', Vigenere.frequencyAnalysis(plain));
        Assert.assertEquals('N', Vigenere.frequencyAnalysis(crypt));

        String stripe = "DUCOFIJMA";
        Assert.assertEquals("DOJ", Vigenere.stripe(stripe, 0, 3));
        Assert.assertEquals("UFM", Vigenere.stripe(stripe, 1, 3));
        Assert.assertEquals("CIA", Vigenere.stripe(stripe, 2, 3));
    }
}
